package org.techtown.sugang;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LectureSearch.java
//  @ Date : 2023-05-27
//  @ Author :
//
//


import android.content.Context;
import android.os.Build;

import androidx.annotation.RequiresApi;

import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.toolbox.Volley;

import java.util.ArrayList;
import java.util.HashMap;

public class ApplicationForClassesDel {

	private String delStdId;
	private String delLectureNo;
	private Context context;

	RegistrationDB registrationDelRequest;

	public void setContext(Context context) {this.context = context;}

	@RequiresApi(api = Build.VERSION_CODES.N)
	public void deleteBtnClick(String Lecture_no, String StdId) {
		this.delLectureNo = Lecture_no;
		this.delStdId = StdId;

		System.out.println("삭제 / delStdId : " + Lecture_no + ", delStdId: " + StdId);
		Response.Listener<String> responseListener = new Response.Listener<String>() {
			@Override
			public void onResponse(String response) {}
		};
		registrationDelRequest = new RegistrationDB(this.delLectureNo, this.delStdId, "Del", responseListener);
		RequestQueue queue = Volley.newRequestQueue(context.getApplicationContext());
		queue.add(registrationDelRequest);

	}

}