package org.techtown.sugang;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LectureSearch.java
//  @ Date : 2023-05-27
//  @ Author :
//
//


import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Build;
import android.util.Log;
import android.widget.ListView;
import android.widget.RadioGroup;
import android.widget.SimpleAdapter;
import android.widget.Toast;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;

import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.toolbox.Volley;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

@RequiresApi(api = Build.VERSION_CODES.N)
public class LectureSearch {


	private int check;
	private String lecture_no;
	private ArrayList<HashMap<String, String>> arr;
	private Context context;

	LectureDB lectureRequest;

	LectureSearch(Context context, String Lecture_no) {
		this.lecture_no = Lecture_no;
		this.context = context;
	}

	public void radioBtnClick(RadioGroup group, int check) {
		this.check = check;
	}



	@RequiresApi(api = Build.VERSION_CODES.N)
	public CompletableFuture<ArrayList<HashMap<String, String>>> searchBtnClick(String lecture_no, String userID, int check) {
		this.lecture_no = lecture_no;
		System.out.println("onResponse 밖");


		CompletableFuture<ArrayList<HashMap<String, String>>> future = new CompletableFuture<>();
		Response.Listener<String> responseListener = new Response.Listener<String>() {
			@Override

			public void onResponse(String response) {
				try {

					JSONArray jsonArray = new JSONArray(response);
					arr = new ArrayList<HashMap<String, String>>();

					System.out.println("onResponse 중");
					for (int i = 0; i < jsonArray.length(); i++) {
						JSONObject jsonObject = jsonArray.getJSONObject(i);
						String json = jsonObject.toString();
						Log.v("msg", json);
						String type = jsonObject.getString("type");
						String lecture_no = jsonObject.getString("lecture_no");
						String lecture_title = jsonObject.getString("lecture_title");
						String professor = jsonObject.getString("professor");
						String headcount_basket = jsonObject.getString("headcount_basket");
						String time = jsonObject.getString("time");


						HashMap<String, String> arrMap = new HashMap<String, String>();
						arrMap.put("lecture_no", lecture_no);
						arrMap.put("lecture_title", lecture_title);
						arrMap.put("professor", professor);
						arrMap.put("type", type);
						arrMap.put("headcount_basket", headcount_basket);
						arrMap.put("time", time);

						arr.add(arrMap);

					}
					future.complete(arr);

					System.out.println(future);
					Log.d("notice", "for 문 시작후");
					Log.d("jsonArray.length", Integer.toString(jsonArray.length()));


				} catch (JSONException e) {
					e.printStackTrace();
				}

			}

		};

		lectureRequest = new LectureDB(lecture_no, userID, check, responseListener);
		RequestQueue queue = Volley.newRequestQueue(context.getApplicationContext());
		queue.add(lectureRequest);
		System.out.println("onResponse 1");

		System.out.print(arr);
		return future;
	}

}