package org.techtown.sugang;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShopingBasketAdd.java
//  @ Date : 2023-05-28
//  @ Author :
//
//

import android.content.Context;
import android.widget.Toast;

import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.Volley;

import org.json.JSONException;
import org.json.JSONObject;

public class ShoppingBasketAdd {
	private String addLectureNo;
	private String addStdId;
	private Context context;
	ShoppingBasketDB shoppingBasketAddRequest;
	CheckBasketDB checkBasketRequest;

	public void setContext(Context context) {
		this.context = context;
	}

	public void applicationBtnClick(String StdId, String Lecture_no) {
		addStdId = StdId;
		addLectureNo = Lecture_no;

		// 이미 동일한 과목이 담겨져 있는지 확인하는 로직
		checkBasketForDuplicate();
	}

	private void checkBasketForDuplicate() {
		Response.Listener<String> responseListener = new Response.Listener<String>() {
			@Override
			public void onResponse(String response) {
				try {
					JSONObject jsonResponse = new JSONObject(response);
					boolean isDuplicate = jsonResponse.getBoolean("checkBasket");

					// 이미 동일한 과목인 경우
					if (isDuplicate) {
						Toast.makeText(context, "신청되었습니다.", Toast.LENGTH_SHORT).show();
						System.out.println("장바구니 / addLectureNo : " + addLectureNo + ", addStdId : " + addStdId);
						Response.Listener<String> addResponseListener = new Response.Listener<String>() {
							@Override
							public void onResponse(String response) {
								// 응답을 받았을 때의 처리 로직
							}
						};

						shoppingBasketAddRequest = new ShoppingBasketDB(addLectureNo, addStdId, "Add", addResponseListener);
						RequestQueue queue = Volley.newRequestQueue(context.getApplicationContext());
						queue.add(shoppingBasketAddRequest);
					} else {
						Toast.makeText(context, "이미 동일한 과목이 담겨져 있습니다.", Toast.LENGTH_SHORT).show();
					}
				} catch (JSONException e) {
					e.printStackTrace();
				}
			}
		};

		Response.ErrorListener errorListener = new Response.ErrorListener() {
			@Override
			public void onErrorResponse(VolleyError error) {
				// 에러 발생 시 처리 로직
			}
		};

		checkBasketRequest = new CheckBasketDB(addStdId, addLectureNo, responseListener, errorListener);
		RequestQueue queue = Volley.newRequestQueue(context.getApplicationContext());
		queue.add(checkBasketRequest);
	}
}