package org.techtown.sugang;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShopingBasketDel.java
//  @ Date : 2023-05-28
//  @ Author : 
//
//


import android.content.Context;
import android.widget.Toast;

import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.toolbox.Volley;

import java.util.concurrent.CompletableFuture;

public class ShoppingBasketDel {
	private String addStdId;
	private String addLectureNo;
	private Context context;

	ShoppingBasketDB shopingBasketDelRequest;

	public void setContext(Context context){ this.context = context; }

	public void deleteBtnClick(String StdId, String Lecture_no) {
		addStdId = StdId;
		addLectureNo = Lecture_no;

		System.out.println("장바구니 삭제 > addLectureNo : " + addLectureNo + ", addStdId : " + addStdId);

		Response.Listener<String> responseListener = new Response.Listener<String>() {
			@Override
			public void onResponse(String response) {}
		};

		shopingBasketDelRequest = new ShoppingBasketDB(this.addLectureNo, this.addStdId, "Del", responseListener);
		RequestQueue queue = Volley.newRequestQueue(context.getApplicationContext());
		queue.add(shopingBasketDelRequest);
		System.out.println("response 1");

		Toast.makeText(context, "삭제되었습니다.", Toast.LENGTH_SHORT).show();

	}
}
